### ISSUE TITLE
如何从文本中提取出点的实体及其属性？

### ISSUE THREAD

**Issue by 1315861791** [blmoistawinde/HarvestText#1]
如题。

**Comment by blmoistawinde** [comment]
你好，新版本中的[命名实体识别](https://github.com/blmoistawinde/HarvestText#%E5%91%BD%E5%90%8D%E5%AE%9E%E4%BD%93%E8%AF%86%E5%88%AB)和[依存句法分析](https://github.com/blmoistawinde/HarvestText#%E4%BE%9D%E5%AD%98%E5%8F%A5%E6%B3%95%E5%88%86%E6%9E%90)的功能也许能够为你提供一些帮助。也可以看看具体的一个案例了解一下它们的作用[近代史纲要信息抽取及问答系统(](https://blog.csdn.net/blmoistawinde/article/details/86557070)。不过这些功能也不是尽善尽美的，欢迎提供更多意见。
