### ISSUE TITLE
安装成功，但是使用的时候发现缺少必要的包 “gensim”, 麻烦添加一下

### ISSUE THREAD

**Issue by JBYan** [blmoistawinde/HarvestText#18]
我已经仔细查看过本库的README和之前的Issues，没有发现解决方案。

**问题描述**
安装成功，但是使用的时候发现缺少必要的包 “gensim”

**如何复现**
from harvesttext import HarvestText
ht = HarvestText()

操作系统： win10

python版本：Python 3.7.4

HarvestText版本：

**Comment by blmoistawinde** [comment]
感谢指出，现在已经加上去了
