### ISSUE TITLE
python环境是python2还是python3

### ISSUE THREAD

**Issue by suixinerdongli** [blmoistawinde/HarvestText#2]

**Comment by blmoistawinde** [comment]
个人的测试环境是python3.6。另外建议以后都使用python3哈，python官方对于python2已经不再更新，支持也会在在2020年结束了。

**Comment by suixinerdongli** [comment]
谢谢，我在安装，使用 pip install harvesttext
会出现error: Microsoft Visual C++ 14.0 is required. Get it with "Microsoft Visual C++ Build Tools"这个你有遇到吗？如何解决的呢

**Comment by blmoistawinde** [comment]
我没有这个问题。拿你的错误信息百度了一下，你可以尝试这个博客里的解决方案：
https://blog.csdn.net/weixin_42057852/article/details/80857948
另外，对于这种随手百度就能有很多结果的问题，建议先自己尝试这些办法，不行再来提问哈，否则遇到不太有耐心的可能就不愿意回答了。希望你能解决问题~

**Comment by suixinerdongli** [comment]
好的，谢谢
