### ISSUE TITLE
实体链接功能

### ISSUE THREAD

**Issue by LiqiangJing** [blmoistawinde/HarvestText#21]
您好，请问我只需要识别出句子中的实体的位置，还需要上传实体的类型词典吗？实体类型词典是必须要传的吗?

**Comment by LiqiangJing** [comment]
您的实体链接主要使用了什么算法，或者相关的论文推荐？

**Comment by blmoistawinde** [comment]
第一个问题：

实体类型词典不是必须的，但如果上传的话，可以在`posseg`等函数分词后获得相应词性，否则会默认词性为“添加词”。

第二个问题：

本库目前的实体链接主要是基于对entity_mention_dict里面的mentions的字符匹配，主体是Trie算法。
