### ISSUE TITLE
清洗模块反馈

### ISSUE THREAD

**Issue by 1286584670** [blmoistawinde/HarvestText#26]
## **通过爬虫抓取微博热门语料对HT的清洗模块进行了小测试，故根据返回结果提出反馈：**

![①](https://user-images.githubusercontent.com/57320690/95833711-9a3a2e80-0d6e-11eb-8f4e-22b0e9a652e2.png)
①：每条语料都有”\u200b“

![②](https://user-images.githubusercontent.com/57320690/95831111-37936380-0d6b-11eb-9a61-ee7d430f5fbd.png)
②：中间的博文内容“辛苦了”被洗掉

![③](https://user-images.githubusercontent.com/57320690/95831325-775a4b00-0d6b-11eb-8fd4-61e1245645e1.png)
③：存在特殊表情符号无法处理

![④](https://user-images.githubusercontent.com/57320690/95831536-bee0d700-0d6b-11eb-8536-07fe6b9de074.png)
④：“[]"后的全部内容被洗掉

![⑤](https://user-images.githubusercontent.com/57320690/95831732-fe0f2800-0d6b-11eb-94d4-0920e4b234b1.png)
⑤：中括号内的“[]"包裹的内容被洗掉

![⑥](https://user-images.githubusercontent.com/57320690/95832034-5e05ce80-0d6c-11eb-9e52-6141265dc68d.png)
⑥：除了”\u200b“,HT大多数情况下的表现已经很好

**Comment by blmoistawinde** [comment]
主要的问题类型应该已经修复了，我找到了几个类似的例子，可以见 https://github.com/blmoistawinde/HarvestText/blob/master/tests/hard_text_cleaning.py
```
清洗前： ['捧杀！干得漂亮！[doge] \\u200b\\u200b\\u200b']
清洗后： ['捧杀！干得漂亮！']
清洗前： ['捧杀！干得漂亮！[doge] \u200b\u200b\u200b']
清洗后： ['捧杀！干得漂亮！']
清洗前： ['#缺钱找新浪# 瞎找不良网贷不如用新浪官方借款，不查负债不填联系人。  http://t.cn/A643boyi \n新浪[浪]用户专享福利，[浪]新浪 
产品用的越久额度越高，借万元日利率最低至0.03%，最长可分12期慢慢还！ http://t.cn/A643bojv  http://t.cn/A643bKHS \u200b\u200b\u200b'] 
清洗后： ['#缺钱找新浪# 瞎找不良网贷不如用新浪官方借款，不查负债不填联系人。\n新浪用户专享福利，新浪产品用的越久额度越高，借万元日利
率最低至0.03%，最长可分12期慢慢还！']
清洗前： ['各位大神们🙏求教一下这是什么动物呀！！疑问问]\n\为什么它同时长得有点吓人又有点可爱爱允悲悲]\n\n#thosetiktoks# http://t.cn/A64 \u200b\u200b\u200b']
IC44 \u200b\u200b\u200b']
清洗后： ['各位大神们求教一下这是什么动物呀！\n为什么它同时长得有点吓人又有点可爱\n#thosetiktoks#']
```

---
顺便可以提一下”\u200b“问题的起因，很有意思：
这个字符原本是[不可见字符](https://blog.csdn.net/xc_zhou/article/details/84346608)，直接打印是看不到的。


```python
print('a\u200ba')
```

    a​a
    

会在文本中出现的原因是因为它被裹在了其他数据结构dict/list中，再使用了显式的类型转化为str，就会保留其原始形式

你的代码里的片段：
```
dict_code = json.loads(response)
dict_code = str(dict_code)
```

另一个简单例子：
```python
print(["a\u200ba"])
```

    ['a\u200ba']
    

再加上`\`是转义字符，所以在存储为文件时为了保留真实的`\`，就需要用`\\`的形式保存，就变成了我们最后看到的样子`\\u200b`。

考虑到是否存储为了文件（出现了双斜杠转义，这边采用了两种清洗方法）


```python
# 未转义
re.sub(r"[\u200b-\u200d]", "", 'a\u200bb\u200dc')
# 已转义
re.sub(r"(\\u200b|\\u200c|\\u200d)", "", 'a\\u200bb\\u200dc')
```




    'abc'




```python
re.sub(r"(\\u200b|\\u200c|\\u200d)", "", 'a\\u200bb\\u200dc')
```




    'abc'
