### ISSUE TITLE
ModuleNotFoundError: No module named 'harvesttext.algorithms'

### ISSUE THREAD

**Issue by learnpythontheew** [blmoistawinde/HarvestText#27]
我已经仔细查看过本库的README和之前的Issues，没有发现解决方案。

**问题描述**
ModuleNotFoundError: No module named 'harvesttext.algorithms'

**如何复现**
直接运行的examples/basic.py 文件

操作系统：

python版本：

HarvestText版本：

**Comment by blmoistawinde** [comment]
刚刚的commit应该可以修复这个问题，可以把github上最新的版本clone或者pull下来，再 `python setup.py install`安装一下试试，如果还有问题我再reopen看看

**Comment by learnpythontheew** [comment]
> 刚刚的commit应该可以修复这个问题，可以把github上最新的版本clone或者pull下来，再 `python setup.py install`安装一下试试，如果还有问题我再reopen看看

我把algorithms 那个文件夹直接贴进packages 里的对应文件夹就可以运行了。
小白问一下如果要安装新版本的话 直接运行命令 pip -- upgrade harvesttext ，文件会更新吗？还是必须要python setup.py install 安装？

**Comment by blmoistawinde** [comment]
pip 是基于pypi的远程托管库才能够发挥作用的，所以`pip install --upgrade harvesttext`只有在pypi上对应的库有发布新版本的时候会自动更新版本。

但是考虑到pip上的更新相对于github上的更新可能有延迟，还有一些库在github上的更新积攒到一定程度后才会把新版上传到pip。所以如果想要第一时间使用上github的更新，建议从github上拉下来更新直接安装。
