### ISSUE TITLE
url正则匹配好像有点问题

### ISSUE THREAD

**Issue by fatguy96** [blmoistawinde/HarvestText#28]
JJ棋牌数据4.3万。数据链接http://www.jj.cn/，数据第一个账号，第二个密码，95%可登录，可以登录官网查看数据是否准确

将 数据第一个账号等都过滤了

**Comment by blmoistawinde** [comment]
刚刚调整了一下正则，原来的正则没有考虑到中文的逗号可以作为URL的截断。调整后对于这个case应该没有问题了。稍微等一段时间，更新的版本上线了以后。你再`pip install -U harvesttext`试试吧
