### ISSUE TITLE
url正则表达式卡死

### ISSUE THREAD

**Issue by JaheimLee** [blmoistawinde/HarvestText#33]
我已经仔细查看过本库的README和之前的Issues，没有发现解决方案。

**问题描述**
某些文本正则表达式会卡死

**如何复现**
“#王一博百里弘毅# wyb#王一博风起洛阳#@二哈啃鸡腿 @YB甜甜的小可爱 //@Knife-Peace反黑站 【1/25】今日五再来‼️‼️裙👉🏻O网页链接目标打卡人数：3000打卡模版 见评论⭕️评论时请同步@ xxx@\xa0 xxx 两位好友•不要@ 你哥⭕️打卡完请顺手转发，转发不带tag✅微博「有害•暴恐」      1.https://service.account.weibo.com/reportspamobile?rid=4597215374620241&type=2&from=400002.https://service.account.weibo.com/reportspamobile?rid=4597257192873019&type=1&from=400003.https://service.account.weibo.com/reportspamobile?rid=4597238372241607&type=1&from=400004.https://service.account.weibo.com/reportspamobile?rid=4597253895883962&type=1&from=400005.https://service.account.weibo.com/reportspamobile?rid=4597261051368482&type=1&from=400006.https://service.account.weibo.com/reportspamobile?rid=4597256013743185&type=1&from=400007.https://service.account.weibo.com/reportspamobile?rid=4597258354169688&type=1&from=400008.https://service.account.weibo.com/reportspamobile?rid=4597253216408617&type=1&from=400009.https://service.account.weibo.com/reportspamobile?rid=4597257359852121&type=1&from=40000✅主页「人身攻击+同步拉黑」⚠️人身攻击模板已更新见评论（按正序查看）1.https://service.account.weibo.com/reportspamobile?rid=7315070554&type=3&from=400002.https://service.account.weibo.com/reportspamobile?rid=7405781810&type=3&from=400003.https://service.account.weibo.com/reportspamobile?rid=7521879541&type=3&from=400004.https://service.account.weibo.com/reportspamobile?rid=6605423447&type=3&from=400005.https://service.account.weibo.com/reportspamobile?rid=5344089965&type=3&from=400006.https://service.account.weibo.com/reportspamobile?rid=6742563952&type=3&from=400007.https://service.account.weibo.com/reportspamobile?rid=1708151137&type=3&from=40000(批皮黑：ID：我们翘课吧）8.https://service.account.weibo.com/reportspamobile?rid=5161857914&type=3&from=400009.https://service.account.weibo.com/reportspamobile?rid=2060991762&type=3&from=40000(批皮黑,ID：Y/i/b/o_姐姐）10.https://service.account.weibo.com/reportspamobile?rid=5470126181&type=3&from=4000011.https://service.account.weibo.com/reportspamobile?rid=2697131254&type=3&from=40000⭕ 今日一：O网页链接⭕ 今日二：O网页链接⭕ 今日三：O网页链接⭕ 今日四：O网页链接历史查询👉🏻 O微博社区管理中心 d\x014597294076798896\x010”

操作系统：Ubuntu18.04

python版本：3.8.5

HarvestText版本：0.8

**Comment by JaheimLee** [comment]
用旧版的去除方式是不会卡死的

**Comment by blmoistawinde** [comment]
换了一套正则表达式，可以现在再试试效果？

**Comment by JaheimLee** [comment]
> 换了一套正则表达式，可以现在再试试效果？

现在测试没发现问题了。

**Comment by JaheimLee** [comment]
> 换了一套正则表达式，可以现在再试试效果？

现在测试没发现问题了。
