### ISSUE TITLE
clean_txt卡死

### ISSUE THREAD

**Issue by kevin2018pg** [blmoistawinde/HarvestText#36]
我已经仔细查看过本库的README和之前的Issues，没有发现解决方案。

**问题描述**
清洗文本卡死 "某某车评栏目称特斯拉自动驾驶技术完败于小鹏 p7 和蔚来，三者对比如何？小鹏p7以及蔚来的感受如何？?-?回答作者：Xiiiiiiii Yoooo?https://zhuanlan.zhihu.com/p/349020455（想看更多？下载?@知乎?App：http://t.cn/RxkY6mK） ??"

操作系统：win10

python版本：py3.7

HarvestText版本：0.8.1.1

**Comment by blmoistawinde** [comment]
用默认参数不能复现这个问题，是否这段文本与实际用的有差别？还是使用了其他的参数？请补充更多细节帮助我判断问题：
![image](https://user-images.githubusercontent.com/32953014/115013417-9769f300-9ee3-11eb-9dea-d52c907dae2c.png)
```python
In [24]: text2 = "某某车评栏目称特斯拉自动驾驶技术完败于小鹏 p7 和蔚来，三者对比如何？小鹏p7以及蔚来的感受如何？?-?回答作者：X 
    ...: iiiiiiii Yoooo?https://zhuanlan.zhihu.com/p/349020455（想看更多？下载?@知乎?App：http://t.cn/RxkY6mK） ??"

In [25]: ht.clean_text(text2)
Out[25]: '某某车评栏目称特斯拉自动驾驶技术完败于小鹏 p7 和蔚来，三者对比如何？小鹏p7以及蔚来的感受如何？?-?回答作者：Xiiiiiiii 
Yoooo? ??'
```

**Comment by blmoistawinde** [comment]
另外为了修复 https://github.com/blmoistawinde/HarvestText/issues/33 换了一套正则表达式，你也可以现在再试试效果？
