### ISSUE TITLE
信息检索

### ISSUE THREAD

**Issue by v-yunbin** [blmoistawinde/HarvestText#40]
我已经仔细查看过本库的README和之前的Issues，没有发现解决方案。

**问题描述**
信息检索结果为空

**如何复现**
from harvesttext import HarvestText
ht = HarvestText()
docs = ["武磊威武，中超第一射手！",
		"郜林看来不行，已经到上限了。",
		"武球王威武，中超最强前锋！",
		"武磊和郜林，谁是中国最好的前锋？"]
inv_index = ht.build_index(docs)
print(ht.get_entity_counts(docs, inv_index)) 

操作系统：windows

python版本：Python 3.8.5

HarvestText版本：0.8.1.4

**Comment by blmoistawinde** [comment]
您好，您应该是从README直接拉下来的这部分代码吧。然而这个上面的代码示例只是一个节选，完整的代码在https://github.com/blmoistawinde/HarvestText/blob/fae00fff2088f43a379726ef83d5c85567a9cd74/examples/basics.py#L86
实际上在运行这段代码之前, ht已经先使用
```
entity_mention_dict = {'武磊': ['武磊', '武球王'], '郜林': ['郜林', '郜飞机'], '前锋': ['前锋'], '上海上港': ['上港'], '广州恒大': ['恒大'],
                           '单刀球': ['单刀']}
entity_type_dict = {'武磊': '球员', '郜林': '球员', '前锋': '位置', '上海上港': '球队', '广州恒大': '球队', '单刀球': '术语'}
ht.add_entities(entity_mention_dict, entity_type_dict)
```
添加了想要检索的实体，这样我们才能够得到这些实体的数量。而您的示例中并没有先添加想要统计的实体，所以会返回空的结果。

所以想要正常使用本功能的话，需要先确定您关心的实体有哪些，使用`add_entities`来添加他们。如果您不希望人工指定实体，而希望模型能够自动发现的话，可以使用`named_entity_recognition`函数先进行自动识别，然后再把识别的结果添加进去。
