### ISSUE TITLE
pip下载的harvesttext版本落后

### ISSUE THREAD

**Issue by Singal0927** [blmoistawinde/HarvestText#41]
我已经仔细查看过本库的README和之前的Issues，没有发现解决方案。

**问题描述**
您好！请问为什么我用pip下载harvesttext的版本为0.4.1呢？使用pip install --upgrade harvesttext后也没用。谢谢！

**如何复现**

操作系统：

python版本：
3.9
HarvestText版本：

**Comment by blmoistawinde** [comment]
您好，我在自己的python 3.6和python 3.7环境上无法复现您的问题，pip安装的结果会是最新的0.8.16

您可以先尝试指定版本`pip install harvesttext==0.8.1.6`

如果不能安装成功，可能与python版本有关，毕竟3.9是比较新的版本，harvesttext较新版本的一些依赖库可能不提供对这个版本的支持，导致您无法安装成功。您可以切换一些3.6, 3.7之类的版本环境来安装新版。

希望能解决您的问题，也希望您能够反馈您后续的尝试结果，帮助我们确认问题，谢谢！

**Comment by Singal0927** [comment]
您好！我将python换成3.8后成功解决了问题，原因是有一个名为“什么什么nlp”（原谅我记不得名称了）的库不支持py3.9.

**Comment by blmoistawinde** [comment]
应该是pyhanlp，感谢你的反馈~
