### ISSUE TITLE
劳烦在码仓里添加一下引文格式

### ISSUE THREAD

**Issue by Myoontyee** [blmoistawinde/HarvestText#49]
**描述你想要的功能**
劳烦在码仓里添加一下引文格式

**是否有自己想过的可能解决方案？**
有，这不您写的我们引起来放心

**其他想说的**
像下面这样的
```
@misc{blmHar???,
title={HarvestText : ????},
author={???},
journal = {GitHub repository},
howpublished = {\url{https://github.com/blmoistawinde/HarvestText}},
year={???}
}
```

**Comment by blmoistawinde** [comment]
感谢建议，现在已经添加到readme
```
@misc{zhangHarvestText,
	author = {Zhiling Zhang},
	title = {{G}it{H}ub - blmoistawinde/{H}arvest{T}ext},
	journal = {GitHub repository},
	howpublished = {\url{https://github.com/blmoistawinde/HarvestText}},
	year = {2023}
}
```

**Comment by Myoontyee** [comment]
title可以改一下，现在这样的title出现在paper里还稍微差一点意思，我有一个建议：
HarvestText : A Toolkit for Text Mining and Preprocessing 

另Readme目前看起来比较麻烦，是否可以从如下状态
```
print("各种清洗文本")
ht0 = HarvestText()
# 默认的设置可用于清洗微博文本
text1 = "回复@钱旭明QXM:[嘻嘻][嘻嘻] //@钱旭明QXM:杨大哥[good][good]"
print("清洗微博【@和表情符等】")
print("原：", text1)
print("清洗后：", ht0.clean_text(text1))
```

改成输出结果直接在代码块下面，这样不用上下翻动，能更方便的理解你的函数库
```
print("各种清洗文本")
ht0 = HarvestText()
# 默认的设置可用于清洗微博文本
text1 = "回复@钱旭明QXM:[嘻嘻][嘻嘻] //@钱旭明QXM:杨大哥[good][good]"
print("清洗微博【@和表情符等】")
print("原：", text1)
print("清洗后：", ht0.clean_text(text1))

>>>各种清洗文本
>>>清洗微博【@和表情符等】
>>>原： 回复@钱旭明QXM:[嘻嘻][嘻嘻] //@钱旭明QXM:杨大哥[good][good]
>>>清洗后： 杨大哥
```

**Comment by blmoistawinde** [comment]
> title可以改一下，现在这样的title出现在paper里还稍微差一点意思，我有一个建议： **HarvestText : A Toolkit for Text Mining and Preprocessing**
> 
> ```
> @misc{zhangHarvestText,
> 	author = {Zhiling Zhang},
> 	title = {HarvestText : A Toolkit for Text Mining and Preprocessing},
> 	journal = {GitHub repository},
> 	howpublished = {\url{https://github.com/blmoistawinde/HarvestText}},
> 	year = {2023}
> }
> ```

哈哈，这确实是很多system/demo paper的起名风格，可以，现在已经修改。

另外readme里面也对比较长的代码结果做了分块展示
