### ISSUE TITLE
how can i add the new words with pos_tag into jieba usedict??

### ISSUE THREAD

**Issue by marcusau** [blmoistawinde/HarvestText#8]
<img width="1568" alt="Screenshot 2019-07-07 at 8 53 50 PM" src="https://user-images.githubusercontent.com/31444195/60768685-70b93e80-a0f9-11e9-9cc7-0b55697b47f4.png">

I have used the command : ht.add_new_words(new_words1) 

however, when running the posseg function, the words i just add to the userdict are still showns as 新詞

Thanks

**Comment by blmoistawinde** [comment]
Please use `ht.add_new_entity` if you want to specify POS. This is the example I've provided in README, 
where I registered a new word "落叶球" with POS="术语".
```python3
def new_word_register():
    new_words = ["落叶球","666"]
    ht.add_new_words(new_words)   # 作为广义上的"新词"登录
    ht.add_new_entity("落叶球", mention0="落叶球", type0="术语")  # 作为特定类型登录
    print(ht.seg("这个落叶球踢得真是666", return_sent=True))
    for word, flag in ht.posseg("这个落叶球踢得真是666"):
        print("%s:%s" % (word, flag), end=" ")
```
```
这个:r 落叶球:术语 踢:v 得:ud 真是:d 666:新词
```
